### ISSUE TITLE
音量変更時の数秒ディレイを無くす

### ISSUE THREAD

**Issue by snakazawa** [unblee/jukebox#106]
Streamを理解すれば行けそうな気がする。

**Comment by snakazawa** [comment]
曲変更時にもディレイあるね。

**Comment by sunya9** [comment]
音声の変更適用バッファと、そのバッファがスピーカーにでるまでのラグが原因な気がするけど、内部バッファを減らしてもうまくいかなくて諦めましたね…（少なくし過ぎると今度はうまく再生してくれなくて難しい）。

**Comment by snakazawa** [comment]
SpeakerStream内でバッファが溜まってるよなぁ。

**Comment by sunya9** [comment]
highWaterMarkをいけそうな気がするってやって無限に失敗したので頑張って欲しい

**Comment by snakazawa** [comment]
highWaterMark、なんも変わんねぇｗ

**Comment by sunya9** [comment]
そうだよ(便乗)

**Comment by snakazawa** [comment]
動作的にはwriteの戻り値がfalseになるだけだから、書き込む側が良い感じにバッファリングするような実装になってないと意味ないっぽい（たぶん）

**Comment by sunya9** [comment]
書き込む側と書き込まれる側を意識して実装する必要がありそう

**Comment by snakazawa** [comment]
これ！！ https://www.npmjs.com/package/readable-buffer-stream
DL数少ないけど、コード見る感じよさげ。 https://github.com/DavidCai1993/readable-buffer-stream/blob/master/src/index.js

**Comment by snakazawa** [comment]
変わらない 😇

**Comment by snakazawa** [comment]
マジでスピーカーの前に何か挟むと半分ぐらいの速度になるのなんなんだｗ

**Comment by sunya9** [comment]
わかる（わからない）

**Comment by snakazawa** [comment]
何も処理しない（横に流すだけ）のTransformStreamを挟んでも遅くなる 🤔 
PassThrough挟んでも遅くなる。
？？？

**Comment by sunya9** [comment]
介入は許されないのか…

**Comment by snakazawa** [comment]
あーー、わかったかも。適切なchunkで送らないとダメなのかも。かも（かも）。

**Comment by snakazawa** [comment]
違う気がするなぁ。適当にやってくれてる気がするなぁ（読めない） https://github.com/TooTallNate/node-speaker/blob/master/index.js#L98

**Comment by snakazawa** [comment]
完全に理解した

[node\-speaker/index\.js at master · TooTallNate/node\-speaker](https://github.com/TooTallNate/node-speaker/blob/master/index.js#L184)
[node\-lame/decoder\.js at master · TooTallNate/node\-lame](https://github.com/TooTallNate/node-lame/blob/master/lib/decoder.js#L147)

**Comment by snakazawa** [comment]
結局これ終わってなかった 😞

**Comment by sunya9** [comment]
がんばってほしい :pray:

**Comment by snakazawa** [comment]
speakerパッケージのDEBUGをONにしてログ見たら、STOP時に書き込み止まってても数秒曲流れ続けるし、Cのコード読まないといけないのでは...？

**Comment by snakazawa** [comment]
https://github.com/TooTallNate/node-speaker/issues/13

**Comment by snakazawa** [comment]
これ挟めばネイティブいじらなくてもいけるかも。

https://github.com/TinyMan/node-timed-stream
