### ISSUE TITLE
ロゴ欲しい

### ISSUE THREAD

**Issue by unblee** [unblee/jukebox#11]
ファビコン欲しい

**Comment by sunya9** [comment]
どんなロゴがいいんだろう

**Comment by unblee** [comment]
まあ一番単純なのは波形で jukebox っていう文字列をトリミングするとか

**Comment by sunya9** [comment]
アイコンというよりロゴだった（それはそうだ）

**Comment by unblee** [comment]
まあファビコンにも使いたいからファビコンにも使えそうな感じが良い（曖昧）

**Comment by kaseiaoki** [comment]
![icon](https://user-images.githubusercontent.com/7625781/28916121-1b695890-787c-11e7-9e24-8b2e29f742b7.png)
たたき台に、こんなでどうですか？

**Comment by unblee** [comment]
ロゴの形は良さげな感じ

**Comment by unblee** [comment]
なんかぼやけてない？

**Comment by kaseiaoki** [comment]
後で色などは調整します

**Comment by kaseiaoki** [comment]
unbleeさんカラーver
![juke](https://user-images.githubusercontent.com/7625781/28976437-d77173fe-7978-11e7-8aea-a08b375dd090.png)

**Comment by kaseiaoki** [comment]
これか、↑の案でどうですか？
![juke](https://user-images.githubusercontent.com/7625781/28977319-8e3ae7fc-797c-11e7-8dd4-ec0a5f529f41.png)

**Comment by kaseiaoki** [comment]
[juke.zip](https://github.com/unblee/jukebox/files/1201032/juke.zip)
正方形verのSVGです

**Comment by kaseiaoki** [comment]
[jukebox.zip](https://github.com/unblee/jukebox/files/1201034/jukebox.zip)
長方形verのSVGです

**Comment by unblee** [comment]
良さげ

**Comment by unblee** [comment]
ファビコンはこれでいきたい
あとは `jukebox` っていう文字列との組み合わせ（WebUI で表示されるタイトル部分）

**Comment by kaseiaoki** [comment]
[juke.zip](https://github.com/unblee/jukebox/files/1202164/juke.zip)
こんどこそ大丈夫なはずです　納めて下さい

**Comment by kaseiaoki** [comment]
[juke.zip](https://github.com/unblee/jukebox/files/1202175/juke.zip)
修正版です

**Comment by kaseiaoki** [comment]
[juke.zip](https://github.com/unblee/jukebox/files/1202192/juke.zip)
修正版の修正版です

**Comment by kaseiaoki** [comment]
[juke.zip](https://github.com/unblee/jukebox/files/1202196/juke.zip)

**Comment by kaseiaoki** [comment]
遅くなりました、おそらくは大丈夫
[juke.zip](https://github.com/unblee/jukebox/files/1202602/juke.zip)

**Comment by unblee** [comment]
アルファ領域を正方形にしてほしい

**Comment by unblee** [comment]
下の直線部分は角が欠けてるけど、上のアーチ部分は欠けてない

**Comment by unblee** [comment]
http://www.1001fonts.com/sanidana-font.html
`jukebox` っていう文字列部分のフォントはこれでいきたい

**Comment by kaseiaoki** [comment]
すみません　こちらを確認してませんでした、直します

**Comment by kaseiaoki** [comment]
>下の直線部分は角が欠けてるけど、上のアーチ部分は欠けてない
これはそういうデザインのつもりなんですけどなおしますか？(jukeboxのシルエットがモデルなので)

**Comment by kaseiaoki** [comment]
[juke.zip](https://github.com/unblee/jukebox/files/1203183/juke.zip)
正方形

**Comment by unblee** [comment]
![jukebox_icon](https://user-images.githubusercontent.com/7700969/29004740-dd22f544-7b07-11e7-9d1a-ec502e154d63.png)

**Comment by unblee** [comment]
![jukebox_logo](https://user-images.githubusercontent.com/7700969/29004741-e2a5bef2-7b07-11e7-99db-60579cc90857.png)

**Comment by unblee** [comment]
[jukebox_icon.zip](https://github.com/unblee/jukebox/files/1203198/jukebox_icon.zip)

**Comment by unblee** [comment]
@kaseiaoki の案を基に作ってみた

**Comment by unblee** [comment]
候補の一つに立候補

**Comment by sunya9** [comment]
めっちゃすき

**Comment by snakazawa** [comment]
うおお、タイトル良い

**Comment by unblee** [comment]
@kaseiaoki からも OK もらったし反応見るに良さげなので（グダグダするのも面倒なので）僕が上げたやつで行きます！
