### ISSUE TITLE
開発時サーバーが落ちた時に自動的に再起動して欲しい

### ISSUE THREAD

**Issue by sunya9** [unblee/jukebox#116]
rs打つのも面倒。

ログが飛ばされて見返しづらくなる可能性はある。

**Comment by snakazawa** [comment]
ttps://github.com/remy/nodemon/issues/175

nodemonだと面倒

**Comment by sunya9** [comment]
なんか2chみたいなURLでワロタ そうなんですよね 地味にそういう機能ないっていう 載ってる方法もscriptsにのせればかわらないとはいえ、あんまり綺麗な方法じゃないなあ

**Comment by sunya9** [comment]
要らない気がしてきたしいい感じの解決方法見当たらないので一旦閉じる
