### ISSUE TITLE
各アクションの正常時のリアクションが欲しい

### ISSUE THREAD

**Issue by snakazawa** [unblee/jukebox#120]
Play, Nextなどのボタンや、HistoryのAddボタンなどを押して処理が完了した際に何かしらのリアクションを表示したい。

**Comment by sunya9** [comment]
通知が欲しいっすね

**Comment by sunya9** [comment]
https://github.com/euvl/vue-notification

**Comment by snakazawa** [comment]
ささやかな通知にしたいんだよなぁ

**Comment by snakazawa** [comment]
とりあえずはこれでもいいのかしら（適当にデザイン調整すればいいし）

**Comment by sunya9** [comment]
過剰ではある気がするので http://bulma.io/documentation/elements/notification/ とか適当に使ってちっこく表示しておけば良さそう（一番の問題は表示する場所なきがする）。

**Comment by snakazawa** [comment]
無いとE2Eテストがキツイ（適当な時間待つみたいなことしてる）ので、とりあえず叩き台として入れますね。

**Comment by snakazawa** [comment]
通知、ユーザー的にほんとに要るのか...？って気持ちになってきた

**Comment by snakazawa** [comment]
現状でも見ればわかる操作： 曲全削除、曲削除、曲選択、曲移動、タブ切り替え、曲再生、曲中断、曲再開、次の曲、前の曲、リスタート、ループモード切替、シャッフルモードON/OFF、音量変更、ミュート/
何かしら反応が欲しい操作： 曲追加、履歴から曲追加、リンクコピー

**Comment by sunya9** [comment]
ぶっちゃけ通知自体は必要なさそうな気がしますね…テスト目的にUI追加するのってなんか違うし

**Comment by snakazawa** [comment]
煩いだけだよね、たぶん。
曲追加、履歴から曲追加、リンクコピーは何かしらのアクションは欲しいなって。

**Comment by sunya9** [comment]
全部は思いつかないですけど、履歴から曲追加とかは追加した時点でタブを光らせるとかどうでしょう

**Comment by snakazawa** [comment]
良さげ...かも。
Playlistに曲数のバッジ付けて、それを（エフェクト付きで）変化させるのもよさそう。

**Comment by sunya9** [comment]
お、普通に曲数バッジはいいんじゃないですか わかりやすいし、それなりに役に立つ表示ではありそう

**Comment by snakazawa** [comment]
曲追加は、inputフィールドの右らへん（Submitボタンの左）に5秒ぐらい文章表示しようかなぁ。

**Comment by sunya9** [comment]
追加は現状プレイリストとキューが一緒ですし、同じくタブを見ればよいのでは？

**Comment by snakazawa** [comment]
ところが、曲数が多いと追加されたか微妙に分からないんですよね。
バッジがあってそれが動けばそれで充分な可能性もある。
でも、追加されたばっかりの曲は強調表示してほしい。特にシャッフル時なんかはどこに追加されたか謎になるんですよね。

**Comment by sunya9** [comment]
個人的にはバッジで推したい。追加された曲の位置については、あのリストの概念から行くと一番後ろに追加されるのが直感的だと思うんですけど、ランダム再生だと一番後ろに追加されない感じなんですかね？
キューとプレイリストが一緒なのもあれですが、ランダム再生でもキューに追加は一番後ろに追加するか、分けたほうがいいように思います。

**Comment by snakazawa** [comment]
キューとプレイリストを分けるともはや別のものになっちゃう気がするですよねぇ。
うーん、どこに入れるかはちょい保留で、バッジ表示をまず入れてみます。

**Comment by snakazawa** [comment]
TODO:
- [ ] Copy Linkのリアクション

**Comment by sunya9** [comment]
tooltipで良いと思いますよ ただbulmaにはtooltipがないっていう

**Comment by snakazawa** [comment]
そうなんだよね。Issue見たらなんか議論された末に否定されて閉じられてるし。

**Comment by sunya9** [comment]
多分フレームワークとして実装しようとすると面倒な点がかなりあって、Bootstrapがいい例（位置を決めるのにさらに外部ライブラリに依存している）。

でも簡易に実装するならCSSとJSのクラスの切り替えである程度はできると思いますよ。ノリは数が増えた時のクラスの付与のノリで、::before, ::after要素とかを使いつつdata属性にツールチップ表示テキストをぶちこんでcontet要素でそれを表示する…とかが楽な例だと思います。

**Comment by sunya9** [comment]
冷静に考えてみればdata属性使わなくてもcontentプロパティにテキストハードコーディングしても大丈夫っすね。

**Comment by snakazawa** [comment]
なるほど……？
勉強ついでにやってみます。

**Comment by snakazawa** [comment]
閉じても大丈夫かな？

**Comment by sunya9** [comment]
閉じてもいいと思います。

**Comment by snakazawa** [comment]
@unblee 閉じてください。
