### ISSUE TITLE
src直下のファイルをディレクトリに分けたい

### ISSUE THREAD

**Issue by snakazawa** [unblee/jukebox#126]
増えてきたので分けたい。直下には `app.js` あたりだけを入れたい。

**Comment by snakazawa** [comment]
提案1

- src/
    - model/
        - history.js
        - history_item.js
        - jukebox.js
        - player.js
        - player_status.js
        - playlist.js
        - speaker.js
        - track.js
    - store/
        - history_store.js
        - player_status_store.js
    - enum/
        - state.js
        - loop_mode.js
    - router.js
    - app.js

modelという名前は曖昧で好きじゃない。
enumもなんか微妙。

**Comment by sunya9** [comment]
素直にconstantsとかどうですか

**Comment by snakazawa** [comment]
良く使われるディレクトリ名なんですか？

**Comment by sunya9** [comment]
昔reduxで見た気がするけどなんかそんなこともなくなったようなので忘れてください（）

**Comment by snakazawa** [comment]
確かに使ってるプロジェクトもあったので、良いかもしれませんね。

**Comment by snakazawa** [comment]
色々Mergeされたので着手したい。
