### ISSUE TITLE
プログレスバーの実装

### ISSUE THREAD

**Issue by unblee** [unblee/jukebox#4]

**Comment by sunya9** [comment]
ffmpegのseekInput設定すれば実質途中から再生できることを確認した https://www.npmjs.com/package/fluent-ffmpeg#seekinputtime-set-input-start-time

**Comment by snakazawa** [comment]
とりあえず操作できなくてもバーぐらいは出すかという気持ちになった

**Comment by snakazawa** [comment]
プログレスバーによる指定時間への移動、10秒戻る/進む、を実装すべきか否か問題。
僕はあまり使わないのでは？という気持ちだけど、使いそうなら実装の目処は立っているのでやります（キャッシュファイルが増えるけど）。

_Sent from my Docomo SO-01H using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by sunya9** [comment]
シークバーあるなら指定時間への移動くらいあったほうがいいんじゃないかな〜と思います。10秒前後は何から実行できるようにします？あれ以上ボタン設置するのもちょっとごちゃごちゃするかなって感じもするので、キーボード操作のみとか…？（そこまで欲しい機能というわけでもない）

**Comment by snakazawa** [comment]
シークバー移動よりはn秒前後のほうが使いそうなので（あれ結構好き）、いい感じのとこに入れたい気持ち。

**Comment by snakazawa** [comment]
Youtubeやニコニコ動画のUIを参考にするとかかな。

**Comment by sunya9** [comment]
10秒前後、ごちゃごちゃするとは言いましたが、入れるのは全然いいと思います。再生ボタンの左右に配置するのがわかりやすいかな？

**Comment by snakazawa** [comment]
なるほどそこかぁ。
じゃあ、とりあえず実装だけしてみます。

**Comment by snakazawa** [comment]
seek制御、10分未満の曲ならすぐにDLも変換も終わるから、あんまり考えることないんだけどなぁ...
焚火...

**Comment by snakazawa** [comment]
共有します。
Youtubeのbeginオプションは使えないという話。
ttps://github.com/fent/node-ytdl-core/issues/129

それを解決したモジュール。
https://github.com/TinyMan/node-jamy

やっぱTimedStream使うんだなぁと思ったら、それを開発した人でした。

**Comment by snakazawa** [comment]
もしかして：このIssueは閉じられる

**Comment by sunya9** [comment]
できそう

**Comment by unblee** [comment]
#147 マージされたので閉じます
