### ISSUE TITLE
server logが欲しい

### ISSUE THREAD

**Issue by snakazawa** [unblee/jukebox#40]
開発用にログ出力が欲しいです。

本番ではそんなに出してほしくないので、ログレベルを適切に設定したいです。

**Comment by sunya9** [comment]
debugモジュール使うのが無難ですかね

**Comment by snakazawa** [comment]
ですかねぇ。。。（まともにログ管理やったことない）

**Comment by sunya9** [comment]
わかる（なんもわからん）

**Comment by snakazawa** [comment]
debugがnode-speakerで使われていたので挙動を把握したけど、node-speakerのデバッグ名が `speaker` で、`src/speaker.js` と被ってどうしようってなってる

**Comment by sunya9** [comment]
適当にjukeboxっていうプリフィックスつけるとか

**Comment by snakazawa** [comment]
それだ

**Comment by snakazawa** [comment]
debugによるdebugコード、どこまで埋め込むべきか悩ましい...
各メソッドの1行目に `debug('method()')` みたいなコードを埋め込んでるんだけど、これ本当に人がやることなのか？？？みたいな気持ちになってくる。

**Comment by snakazawa** [comment]
debugコード埋め込みの方針を話し合えればなと思います。

やってて思ったこと：
- 副作用のないメソッドにはdebugはいらない (e.g., `Player.serialize(), Player.getVolume()`)
- プロパティの変更はそのプロパティを直接変更するメソッドのみにdebugを入れる (e.g., Player.setLoopMode()にdebugはいらない、PlayerStatus.*LoopMode()に入れる）
- 上に含まれててもあったら嬉しいところには入れる
