### ISSUE TITLE
テストの自動化

### ISSUE THREAD

**Issue by snakazawa** [unblee/jukebox#43]
手動は辛いです。

mocha + power-assertsはいかがでしょうか。
クライアントはわかりません。

**Comment by sunya9** [comment]
クライアント側は.vueファイルじゃないのでテスト方法難しそうっすね。

**Comment by snakazawa** [comment]
.vueってwebpackかなんか挟まないと動かないんだっけ？

**Comment by sunya9** [comment]
基本的にはそれとvue-loader使って変換して取り込む形ですね。他に方法あるのかもしれませんが…。

**Comment by unblee** [comment]
そろそろ Webpack を導入しても良いかもしれない（気は進まないけど

**Comment by snakazawa** [comment]
webpackあれば、enum定義をサーバーとクライアントで使いまわせるんですよねー。
なしでもできる方法も考えますが。

**Comment by sunya9** [comment]
webpack使うか、あえてrollup使うか、挑戦してfusebox使って見るとか？

fuseboxは.vueファイル関連まだっぽいし、無難にいくならwebpackでしょうね…（私もそこまで気は進まない）。

**Comment by unblee** [comment]
webpack 突っ込んでみますかー

**Comment by snakazawa** [comment]
テスト基盤を入れました #62

**Comment by unblee** [comment]
#62 マージしました 👍

**Comment by snakazawa** [comment]
このIssueはどこまでやったらCloseしますか？

**Comment by unblee** [comment]
CI 突っ込むまでいきたい

**Comment by snakazawa** [comment]
なるほど。ではカバレッジ計測も入れますか。

**Comment by unblee** [comment]
入れましょう

**Comment by snakazawa** [comment]
このへん( https://github.com/snakazawa/github2slack/blob/master/package.json ) 参考にして nya を入れますね。

**Comment by unblee** [comment]
👏

**Comment by snakazawa** [comment]
travisのCIだったらこんな感じにやればできます https://github.com/snakazawa/github2slack/blob/master/.travis.yml#L15

**Comment by snakazawa** [comment]
テストの自動化しても、Mergeする前に結局 @unblee 氏が手作業で最終確認しそう。（何か効率化できないかなぁ...）

**Comment by sunya9** [comment]
せやろか（さすがにテストする項目多くなってきたし、UIのチェックとソースコードレビューしかしなさそうな感じしますが）

**Comment by unblee** [comment]
E2E は割り切るしか無いかなと

**Comment by snakazawa** [comment]
ブラウザ勝手に動かしてそれを眺めるだけ、みたいなのを眺めて安心できそうなら、やりたい。

**Comment by snakazawa** [comment]
これ使ってみます: http://nightwatchjs.org/

**Comment by snakazawa** [comment]
e2e testとunit testのカバレッジを統合する方法がわからないというか無さそうなので、諦めます。

http://qiita.com/cognitom/items/27b7375bea653b414c8f#%E3%82%B3%E3%83%BC%E3%83%89%E3%82%AB%E3%83%90%E3%83%AC%E3%83%83%E3%82%B8

**Comment by unblee** [comment]
#75 で E2E テストがマージされました 👍 👍 
@snakazawa ありがとうございました 🙏 🙏

**Comment by snakazawa** [comment]
やったー！！！！！

**Comment by snakazawa** [comment]
Unitテストどこまでやるか問題

**Comment by sunya9** [comment]
言い出したらきりがないし、とりあえず導入したということでこれは一旦閉じても良いのでは（ほか個別にIssue挙がってることだし）。

**Comment by unblee** [comment]
とりあえず単体テスト・E2Eテスト・Travis CI 入ったのでこの issue は閉じます
