### ISSUE TITLE
クライアントで曲をD&Dで曲順変更

### ISSUE THREAD

**Issue by snakazawa** [unblee/jukebox#46]
したい（かも）。

**Comment by snakazawa** [comment]
この辺使う？ https://github.com/SortableJS/Vue.Draggable

**Comment by sunya9** [comment]
良さ気（Vueと相性良さそうなら何でも良さはある）。

**Comment by sunya9** [comment]
実装面倒なので一旦やめ

**Comment by sunya9** [comment]
並び替えするにはトラックに固有のIDを割り振る必要があるのと、再生位置を考慮しなきゃならず面倒なので、まずは再生位置の値をcomputedな感じにしたい

**Comment by snakazawa** [comment]
テストのとき思ったけど、Trackに適当なIDを割り振りたい

**Comment by sunya9** [comment]
頼んだ:pray:

**Comment by snakazawa** [comment]
並び替え、別にID必要なくないですか（indexじゃダメなんか？）

**Comment by sunya9** [comment]
並び替えたらindexは変わるのでは…？

**Comment by snakazawa** [comment]
クライアント側で並び替えイベント時にどの曲が挿入されたかわからんってことか

**Comment by sunya9** [comment]
まあ、なんかやってみれば色々面倒くさそうなことがわかる（丸投げ

**Comment by snakazawa** [comment]
こんな感じじゃいかんのか
https://jsfiddle.net/o5rgwo7L/

**Comment by sunya9** [comment]
いけそう（？） 差し替えるって発想がなかった 再生してる楽曲の位置とかもそこまで複雑じゃなさそうですかね

**Comment by snakazawa** [comment]
状態更新時に全情報を同期してるので、サーバー側に適当に3行ぐらい追加すればいけそう。

**Comment by sunya9** [comment]
:pray:
