### ISSUE TITLE
ブラウザの横幅を狭くするとプレビュー画面が消える

### ISSUE THREAD

**Issue by snakazawa** [unblee/jukebox#50]
![image](https://user-images.githubusercontent.com/6027645/28979029-31abf628-7983-11e7-8232-d0a20dd6ffed.png)

**Comment by sunya9** [comment]
これ今も消えます？（FirefoxとChromeで確認したけど消えなかった）

**Comment by snakazawa** [comment]
曲数0だと消えるようです
