### ISSUE TITLE
履歴機能がちょっと欲しい

### ISSUE THREAD

**Issue by snakazawa** [unblee/jukebox#52]
追加履歴として、項目はuniqueで上限100個ぐらいで良い気がする（上限は環境変数で）。  
デザインが難しい。

**Comment by sunya9** [comment]
bulmaのpanelにtabがあるから、右側のプレイリストのところを切り替えられるようにするといいと思います

**Comment by sunya9** [comment]
同じ曲を再び再生した時の挙動を考えておく必要がありそう。

**Comment by snakazawa** [comment]
再生履歴ではなく追加履歴にするとちょい楽になる

**Comment by snakazawa** [comment]
データ構造に再生回数を追加することで色々解決思想なきがしてきた

**Comment by snakazawa** [comment]
やるかぁという気持ち

**Comment by unblee** [comment]
#90 で実装済み
