### ISSUE TITLE
eslintの追加

### ISSUE THREAD

**Issue by snakazawa** [unblee/jukebox#56]
コード規約どうしましょ。

**Comment by unblee** [comment]
一からルール作るか既存のルールセットを一気に適用するか

**Comment by unblee** [comment]
有名所のルールセットってどんなのがあるんでしょう？

**Comment by sunya9** [comment]
a　i　r　b　n　b

**Comment by unblee** [comment]
airbnb のルール突っ込んでどのくらい怒られるんだろうか

**Comment by sunya9** [comment]
そこまで怒られなさそうな気も（わからん）一部厳し目のルールもあるので最初はカンマとかセミコロンとかクォーテーションくらいの設定くらいでもいい気はする。

**Comment by snakazawa** [comment]
とりあえずiarbnb突っ込んでみますね

**Comment by snakazawa** [comment]
airbnb-baseをextendsしてauto fixで気になった点

1. 配列やオブジェクトの最終行の末尾に `,` が付く  `[a, b, c,]`
2. アロー関数の引数がひとつでもカッコで囲む `(x) => {...}`

**Comment by sunya9** [comment]
あーそれ気になりますよね 個人的にはケツカンマあんまり好きじゃないのと、せっかくのarrow functionが記述しづらくてあれだと思ってるので後者は特に上書きしたい（前者はどっちでもいい、diffが少なくなるという利点はいいと思う）。

**Comment by snakazawa** [comment]
ケツマンマ禁止、単一引数のアロー関数はカッコ禁止でやっちゃいますね

**Comment by snakazawa** [comment]
プロパティ名の先頭アンダースコアも許可します `obj._hoge()`

**Comment by snakazawa** [comment]
クソデカPRを送ってしまった

**Comment by unblee** [comment]
#59 でマージ済み
