### ISSUE TITLE
vuexの適用

### ISSUE THREAD

**Issue by snakazawa** [unblee/jukebox#61]
欲しくなってきた

**Comment by snakazawa** [comment]
この辺が辛いです...
https://github.com/unblee/jukebox/blob/master/assets/js/index.js#L3

**Comment by sunya9** [comment]
どのコンポーネントでも自由に状態を手に入れたいって感じですかね

**Comment by snakazawa** [comment]
それそれ。bindUpdateで更新している手間がなーという。

**Comment by snakazawa** [comment]
よく見たらbindUpdateいらない気がしてきた（$set案件？）

**Comment by sunya9** [comment]
あんまり読み込んでないのでわからないですけど、オブジェクトの更新も、オブジェクト自体を更新するなら$setとかする必要はなかった気がしますよ

**Comment by snakazawa** [comment]
なるほど、だいたい理解できた気がする

**Comment by sunya9** [comment]
vuexあんまり関係ないけどcomputedにしていいところが結構有る気がする（methodの呼び出しをcomputedに切り替えられるところがちょっとある）。

**Comment by snakazawa** [comment]
computedにしたら更新されなくて泣いてる（unblee君も同じことをして諦めてそう）

**Comment by snakazawa** [comment]
普通に出来た（すみません）

**Comment by sunya9** [comment]
ってか、結局vuexは導入する感じなんですかね（いずれ必要になりそうだけど、親子関係で済むならpropsでも良さそうみたいな発想）。

**Comment by snakazawa** [comment]
とりあえずタスクとして書いときますが、後回しでも良いかもです（テストするときは入れたいですね）

**Comment by snakazawa** [comment]
勉強用にやります。
