### ISSUE TITLE
1ループ再生時に次を押しても次の楽曲にいかない

### ISSUE THREAD

**Issue by sunya9** [unblee/jukebox#64]
曲終わりはループが理想だけど、明示的にnextのリクエストを飛ばしたら次の曲へいくのが理想な気がする（前野曲にいくのも同様）。

**Comment by unblee** [comment]
まあ確かに next だったら次の曲に行くっていうのが直感的かもしれない

**Comment by unblee** [comment]
その場合 restart ボタンみたいなのがあっても良いかもしれない

**Comment by sunya9** [comment]
もしくは、1ループ有効ならそもそもボタンを使えないようにするのもありっちゃあり（UX的には微妙そう）

**Comment by unblee** [comment]
one loop 中 next/prev をリクエストした場合次／前の曲に移動する仕様に変更しても良いと思います
ただその場合 restart ボタンみたいなのも同時に実装したいです

**Comment by sunya9** [comment]
再生時間が5秒以降だったら巻き戻し、それより以前だったら前の曲みたいなのもありな気はしますが、いかんせん再生時間とれてないから今はあれかも

**Comment by unblee** [comment]
現状で実装するならそこら辺は考えなくて単純に次/前の曲に移動するぐらいで良いと思います

**Comment by snakazawa** [comment]
Restartボタンが追加されたので、one loopモード時にprev, nextでそれぞれ前の曲、次の曲に移動するように変更します。
