### ISSUE TITLE
travis ci 導入

### ISSUE THREAD

**Issue by unblee** [unblee/jukebox#68]

**Comment by unblee** [comment]
related #43

**Comment by snakazawa** [comment]
E2Eテスト、どうしよ（headless考えないようにしてた）

**Comment by snakazawa** [comment]
Chromeのheadlessモードを入れた。

**Comment by unblee** [comment]
#75 がマージされたらやる

**Comment by snakazawa** [comment]
対応した

**Comment by snakazawa** [comment]
検証中ですが、speakerのstopの中で、unpipeの後にendするように試してみてください。

**Comment by snakazawa** [comment]
逆でした。unpipeの前にendです。

**Comment by snakazawa** [comment]
もうとりあえずSinonでspeakerを上書きして適当にやり過ごしてCI入れない？

**Comment by unblee** [comment]
ここまできたらもう見なかったことにしたい :(

**Comment by snakazawa** [comment]
speaker関係なかった

https://github.com/snakazawa/jukebox/blob/add-travis-config/src/speaker.js#L76
https://travis-ci.org/snakazawa/jukebox/builds/264023736#L1048

**Comment by snakazawa** [comment]
日本語で補足。

`ffmpeg.pipe()` で作ったstreamはただの `PassThrough` ストリームで、このstreamを `end()` してもffmpegのプロセスは止まらないから、`end()` した後も` write()` されて `write after end` エラーが吐かれてるっぽい（っぽい気配を感じた（中身を見て確かめたわけではない））
後詰まりポイントとして、基本的にstreamも、たぶんffmpegの内部処理も非同期処理だから、気を付けないとすぐ死ぬ。

ffmpegのkillはstdinに"q"を送る方法もあったけど、微妙にうまくいかないのでやめた。

**Comment by snakazawa** [comment]
（本当に上の通りならstopしたときは毎回エラー吐かれて死んでいるはずなので、実際は `end()` 時に `kill` 飛んでて、たまに残ってる残るのバッファが吐き出されて死ぬか、非同期処理によりたまに処理順序がずれて死んでる気がする）

**Comment by snakazawa** [comment]
冷静に考えると、 `end()` が生えてるのはReadableStreamなのでこれはバグではなく当然の挙動っぽさある。
`Provider.createStream()` が返すべきは(Any)Streamではなく、殺せるよう拡張した `ReadableStream` に仕様を変更すると良さそう。

**Comment by snakazawa** [comment]
だんだんすごい納得してきてて、CIが最初の方でたまに通って一回落ちたらその後毎回落ちるのはyoutubeのDL速度が関係してて、DLが早ければすぐにstram処理が終わってエラーが出ない（憶測）
