### ISSUE TITLE
ロゴの適用

### ISSUE THREAD

**Issue by unblee** [unblee/jukebox#72]
#11 で使用するロゴを（強行）決定したので WebUI のタイトル部分とかファビコンとかに適用する

**Comment by unblee** [comment]
@sunya9 お頼み申した 🙏 🙏 🙏

**Comment by unblee** [comment]
[jukebox_icon.zip](https://github.com/unblee/jukebox/files/1203283/jukebox_icon.zip)
これ使ってください 🙏

**Comment by unblee** [comment]
あと、README の一番上とかに貼り付けたい

**Comment by sunya9** [comment]
READMEの参照って普通にリポジトリから参照で良いのだろうか

**Comment by unblee** [comment]
それでいけるはず
