### ISSUE TITLE
シャッフルモード切替時の再生中トラックがずれている

### ISSUE THREAD

**Issue by unblee** [unblee/jukebox#73]
期待する動作：
シャッフルモード切り替えボタンを押したら再生中のトラックがプレイリストの一番上に移動する or 移動しなくても再生中トラックがずれることはない

実際の動作：
シャッフルモード切り替えボタンを押したら現在再生中のトラックではなくシャッフル後のプレイリストの一番上のトラックが再生中ということになっている

**Comment by snakazawa** [comment]
あるぇ...

**Comment by unblee** [comment]
fixed #76
