### ISSUE TITLE
[RFC] トラックの dequeue をやめるかどうか

### ISSUE THREAD

**Issue by unblee** [unblee/jukebox#77]
開発スタート時（＆現状）はプレイリスト/oneループを有効にしていない限り再生したトラックは削除（dequeue）する仕様である。この仕様は元々刹那的な運用（プレイリストの使い捨て）を前提にして組み込まれた。
しかし、現時点までにプレイリストの保存や任意トラック（からの再生/の削除）をサポートする等の機能が実装され、プレイリストに対する操作の自由度が向上したことによって、この仕様がアプリケーション UX を損ねるものになっているのではないかと考えた。
よってこの issue で dequeue 仕様を削除するか否かの議論を行いたい。

**Comment by unblee** [comment]
という感じで（僕が仕様に組み込んだわけですが）dequeue 仕様やめてもいいんじゃないかな〜って思ったわけです

**Comment by sunya9** [comment]
Google play musicを常用してる人としての意見だけど、プレイリストとキューの概念が分けると良さそう。プレイリストの曲をクリックするとキューの中身がプレイリストにまるごと入れ替わるのか、みたいなのは考えないといけませんが。

**Comment by snakazawa** [comment]
履歴が実装されればdequeue仕様は生きると思うので、現状のままでもいいかなと。

**Comment by unblee** [comment]
履歴機能が実装されたので dequeue 仕様にも意味があると考え、とりあえず dequeue 仕様は継続で行きたいと思います
