### ISSUE TITLE
`ev` を消したい

### ISSUE THREAD

**Issue by snakazawa** [unblee/jukebox#89]
`src/app.js` で作っているEventEmitterのインスタンスevを使い回すのを辞めたいです。
もしかして: グローバル変数

**Comment by sunya9** [comment]
koaのインスタンス使っちゃいましょう

**Comment by snakazawa** [comment]
そもそも extends EventEmitter で多分事足りる

**Comment by sunya9** [comment]
（そもそもappにeventsが実装されてる）

**Comment by snakazawa** [comment]
そうではなくて、PlayerとかPlaylistにそのままイベント持たせて（extends EventEmitterして）、それを `app.js` で購読したほうが良くない？ということを言いたかったです。

**Comment by sunya9** [comment]
あ、なるほど。それはたしかにそうかも

**Comment by snakazawa** [comment]
koaのインスタンスにも突っ込んでおきたい（テスト用に）

**Comment by unblee** [comment]
#91 で実装済み
